### ISSUE TITLE
AsyncAPI spec v3 support in JSON Schema files

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/asyncapi-node#400]
#### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

Although most changes are actually done here, because it's part of the release flow, there are still some outstanding issues.

### Scope
- [x] Allow Multi-format in JSON Schema files #370
- [x] Release to production (master)

**Comment by fmvilas** [comment]
/progress 90 This issue is mostly solved. We only need to release an RC (release candidate) version AFAIK. @smoya can confirm.

**Comment by smoya** [comment]
> /progress 90 This issue is mostly solved. We only need to release an RC (release candidate) version AFAIK. @smoya can confirm.

The reality is that it is already released https://github.com/asyncapi/spec-json-schemas/releases/tag/v6.0.0-next-major-spec.2

**Comment by smoya** [comment]
/progress 91 a bug fix is required. PR: https://github.com/asyncapi/spec-json-schemas/pull/411

**Comment by derberg** [comment]
Almost there bot
