### ISSUE TITLE
$ref do not work with `bindings` in channel in v3

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi-node#438]
> issue might be with any bindings, not just channel, I did not check

spec says that in channels I can also have `$ref`

![Screenshot 2023-10-31 at 14 17 15](https://github.com/asyncapi/spec-json-schemas/assets/6995927/5c19aa33-90e2-4faa-b91d-6c9b240ca976) 

which makes sense as I want to have some reusable stuff in `components. channelBindings`

I would expect below example to work ([studio direct link](https://studio.asyncapi.com/?base64=YXN5bmNhcGk6ICczLjAuMCcKaW5mbzoKICB0aXRsZTogTXlTbGFja0JvdCBBUEkKICB2ZXJzaW9uOiAnMS4wLjAnCiAgZGVzY3JpcHRpb246ICB8CiAgICBUaGUgTXlTbGFja0JvdCBBcHAgbWFuYWdlcyBwb3B1bGFyIG1lc3NhZ2VzIGluIGEgd29ya3NwYWNlIGJ5IG1vbml0b3JpbmcgbWVzc2FnZSByZWFjdGlvbiBkYXRhIGZyb20gU2xhY2sncyBFdmVudCBBUEkuCiAgICAKc2VydmVyczoKICB3czoKICAgIGhvc3Q6IHdzczovL3dzcy1wcmltYXJ5LnNsYWNrLmNvbS8KICAgIHByb3RvY29sOiB3c3MKICAgIGRlc2NyaXB0aW9uOiAiV2Vic29ja2V0IFVSTCBnZW5lcmF0ZWQgdG8gY29tbXVuaWNhdGUgd2l0aCBTbGFjayIKY2hhbm5lbHM6CiAgcm9vdDoKICAgIGFkZHJlc3M6IC8KICAgIG1lc3NhZ2VzOgogICAgICByZWFjdGlvbkxpc3RlbmVyOiB7fQogICAgICBoZWxsb0xpc3RlbmVyOiB7fQogICAgYmluZGluZ3M6CiAgICAgICRyZWY6ICIjL2NvbXBvbmVudHMvY2hhbm5lbEJpbmRpbmdzL2Nvbm5lY3Rpb25RdWVyeSIKICAgICAgCm9wZXJhdGlvbnM6CiAgaGVsbG9MaXN0ZW5lck9wZXJhdGlvbjoKICAgIGFjdGlvbjogcmVjZWl2ZQogICAgY2hhbm5lbDoKICAgICAgJHJlZjogIiMvY2hhbm5lbHMvcm9vdCIKICAgIG1lc3NhZ2VzOiAKICAgICAgLSAkcmVmOiAiIy9jaGFubmVscy9yb290L21lc3NhZ2VzL2hlbGxvTGlzdGVuZXIiCiAgcmVhY3Rpb25MaXN0ZW5lck9wZXJhdGlvbjoKICAgIGFjdGlvbjogcmVjZWl2ZQogICAgY2hhbm5lbDogCiAgICAgICRyZWY6ICIjL2NoYW5uZWxzL3Jvb3QiCiAgICBtZXNzYWdlczogCiAgICAgIC0gJHJlZjogIiMvY2hhbm5lbHMvcm9vdC9tZXNzYWdlcy9yZWFjdGlvbkxpc3RlbmVyIgoKY29tcG9uZW50czoKICBjaGFubmVsQmluZGluZ3M6CiAgICBjb25uZWN0aW9uUXVlcnk6CiAgICAgIHdzOgogICAgICAgIHF1ZXJ5OiB7fQ%3D%3D) -  btw I love new share button in studio:
```yml
asyncapi: '3.0.0'
info:
  title: MySlackBot API
  version: '1.0.0'
  description:  |
    The MySlackBot App manages popular messages in a workspace by monitoring message reaction data from Slack's Event API.
    
servers:
  ws:
    host: wss://wss-primary.slack.com/
    protocol: wss
    description: "Websocket URL generated to communicate with Slack"
channels:
  root:
    address: /
    messages:
      reactionListener: {}
      helloListener: {}
    bindings:
      $ref: "#/components/channelBindings/connectionQuery"
      
operations:
  helloListenerOperation:
    action: receive
    channel:
      $ref: "#/channels/root"
    messages: 
      - $ref: "#/channels/root/messages/helloListener"
  reactionListenerOperation:
    action: receive
    channel: 
      $ref: "#/channels/root"
    messages: 
      - $ref: "#/channels/root/messages/reactionListener"

components:
  channelBindings:
    connectionQuery:
      ws:
        query: {}
```

but  this says is not allowed
```yml
bindings:
      $ref: "#/components/channelBindings/connectionQuery"
```

After so many years, I still do not feel like JSON Schema expert so can you confirm, but I think in here https://github.com/asyncapi/spec-json-schemas/blob/next-major-spec/definitions/3.0.0/channel.json#L65 we should instead have something like

```json
"bindings": {
      "oneOf": [
        {
          "$ref": "http://asyncapi.com/definitions/3.0.0/Reference.json"
        },
        {
          "$ref": "http://asyncapi.com/definitions/3.0.0/channelBindingsObject.json"
        }
      ]
```

thoughts?

**Comment by fmvilas** [comment]
Yeah, I think it does make sense indeed.

**Comment by derberg** [comment]
@fmvilas @smoya PR opened: https://github.com/asyncapi/spec-json-schemas/pull/442

**Comment by derberg** [comment]
solved in `next-major-spec`
