### ISSUE TITLE
Schema for v2.0.0 does not allow to extend the components object with specification extensions

### ISSUE THREAD

**Issue by balogal** [asyncapi/asyncapi-node#46]
#### Describe the bug
The schema for v2.0.0 (and all older versions) does not allow to extend the [components object](https://github.com/asyncapi/asyncapi-node/blob/master/schemas/2.0.0.json#L251-L332) with specification extensions. This is inconsistent with the [specification](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#componentsObject) which states that the components object can be extended with specification extensions. 

#### How to Reproduce
Validating the following exemplary AsyncAPI document against the [v2.0.0 schema](https://github.com/asyncapi/asyncapi-node/blob/master/schemas/2.0.0.json) with any JSON schema validation library results in an error like _Property 'x-extension' has not been defined and the schema does not allow additional properties_ or similar:
```json
{
    "asyncapi": "2.0.0",
    "info": {"version": "1.0", "title": "Example API"},
    "channels": {},
    "components": {
        "x-extension": "xxx"
    }
}
```

#### Expected behavior
Above AsyncAPI document should be validated without errors.

**Comment by derberg** [comment]
@balogal you are right, `components` should also be "extendable". Can you open a PR with the fix?

**Comment by derberg** [comment]
just 2.0.0 please, 🙇🏼
